### ISSUE TITLE
Update pod image on CRD image changes

### ISSUE THREAD

**Issue by jjhuff** [jthomperoo/custom-pod-autoscaler-operator#53]
Thanks for the handy project!

I noticed that the reconcile process doesn't seem to catch changes in the `image`, so I have to delete the CPA and re-create when testing.

**Comment by jthomperoo** [comment]
Thanks for the feedback, that's really appreciated! That's a good point, the reconcile process in the current version will only create a new resource if the resource doesn't exist yet, it doesn't handle updating an already existing resource - supporting updating would be useful. I'll get working on this and get updating resource support into a new version (will be `v0.6.0`), thanks!
