### ISSUE TITLE
Can i use CPA will work for  predication and sudden spike autoscaling on EKS ?

### ISSUE THREAD

**Issue by nandhyala** [jthomperoo/custom-pod-autoscaler-operator#55]
@jthomperoo 

Can you please let me know CPA will work for predication and sudden spike autoscaling on EKS ?

Thanks !

**Comment by jthomperoo** [comment]
Hi, the Custom Pod Autoscaler Framework has been tested on EKS, it should work. Configuration is fully available as it does not need master node access, in terms of prediction and pre-emptively scaling to avoid sudden latency spikes, the [Predictive Horizontal Pod Autoscaler](https://github.com/jthomperoo/predictive-horizontal-pod-autoscaler) would be suitable for that, I see you've already raised an issue jthomperoo/predictive-horizontal-pod-autoscaler#26 - I think the PHPA is your best bet for this, I've put in an answer there, so I'll close this issue and we can continue the discussion on the other issue you've raised.
