### ISSUE TITLE
Missing WATCH_NAMESPACE variable

### ISSUE THREAD

**Issue by johannesheinz** [jthomperoo/custom-pod-autoscaler-operator#56]
Hi Jamie,

I ran a cluster scoped install, but the operator is in **CrashLoopBackOff** state probably due to the missing `WATCH_NAMESPACE` variable:

```
{"level":"info","ts":1589173446.6930842,"logger":"cmd","msg":"Go Version: go1.13.6"}
{"level":"info","ts":1589173446.6931605,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1589173446.6931858,"logger":"cmd","msg":"Version of operator-sdk: v0.10.0"}
{"level":"error","ts":1589173446.6932368,"logger":"cmd","msg":"Failed to get watch namespace","error":"WATCH_NAMESPACE must be set","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\tcustom-pod-autoscaler-operator/cmd/manager/main.go:89\nruntime.main\n\t/opt/hostedtoolcache/go/1.13.6/x64/src/runtime/proc.go:203"}
```

The initial value in `dist/cluster/operator.yaml` is set to `""`.  Seeting it to `"default"` yields the same error. Any ideas?

**Comment by jthomperoo** [comment]
Hi Johannes,

Thanks for finding that; I can't seem to recreate it however. I've installed on both GKE (K8s `v1.14.10`) and EKS (K8s `v1.14.9`) cluster wide and the operator seems to run fine - very strange.
I installed using this command:
```
VERSION=v0.5.0
curl -L "https://github.com/jthomperoo/custom-pod-autoscaler-operator/releases/download/${VERSION}/cluster.tar.gz" | tar xvz --to-command 'kubectl apply -f -'
```
When I look at the environment variables the `WATCH_NAMESPACE` variable is empty but it is there, it works when that variable is empty.

Maybe could you check if doing a namespace install works?
```
NAMESPACE=<INSERT_NAMESPACE_HERE>
VERSION=v0.5.0
kubectl config set-context --current --namespace=${NAMESPACE}
curl -L "https://github.com/jthomperoo/custom-pod-autoscaler-operator/releases/download/${VERSION}/namespace.tar.gz" | tar xvz --to-command 'kubectl apply -f -'
```
With `NAMESPACE` set to `default` for example, if you could also send me your Kubernetes version too that would be really useful - it might let me recreate this. You can get your K8s version with:
```
kubectl version
```
It should list it under server version.

Thanks for finding this - hopefully we can resolve it!

**Comment by johannesheinz** [comment]
Thanks for your support. I'm not so sure anymore if this is an issue with the operator or my cluster setup: I also had a failure using `kube-prometheus` yesterday. My server version is 1.18.2

I guess I'll test it today on another public cloud to check my setup. I'll let you know the results.

**Comment by johannesheinz** [comment]
Dear Jamie,

sorry for the long delay. I can confirm that the exact same setup works well on a DigitalOcean cluster that I created in the same way from scratch. Specifically I can confirm that it works with ...

- a custom kubeadm setup using callico for networking
- kubernetes 1.18.2
- Ubuntu 20.04
- A custom Docker registry within the cluster

Sorry about the fuss. It must have been a misconfiguration in the cluster setup, probably an issue with the internal network or firewall config.

**Comment by jthomperoo** [comment]
Don't worry about it! Glad that's working now, thanks!
